### ISSUE TITLE
Doesn't seem to work: appserver_1 was not found

### ISSUE THREAD

**Issue by jigarius** [dustinleblanc/lando-rails-example#7]
Hi. Thanks for sharing the landofile. I tried using this but it does't work for me. Does it still work for you? I keep getting errors like `appserver_1` was not found.

I also get:
```
lando-rails-example 12:53:38 ERROR ==> No container found for appserver_1
 
Starting landorailsexample_appserver_1 ... done
Scanning to determine which services are ready... Please standby...
Starting landorailsexample_appserver_1 ... done
Killing landorailsexample_appserver_1 ... error

ERROR: for landorailsexample_appserver_1  Cannot kill container: b7dcbe81230c7ddf06253ad2378a03eb0ea365c6eade25a50d5b88b42c864a83: Container b7dcbe81230c7ddf06253ad2378a03eb0ea365c6eade25a50d5b88b42c864a83 is not running
```

**Comment by dustinleblanc** [comment]
That looks like a random docker issue, you may want to destroy and then rebuild the app

**Comment by jigarius** [comment]
Though I couldn’t get this to work, I finally managed to get my own setup to work, which is documented in this [article](https://jigarius.com/blog/ruby-on-rails-with-lando). Thanks.
